# Generated by Django 6.0.4 on 2026-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Телеграмм ID"),
        ),
    ]
